services:
  api:
    build:
      context: .
      target: api
    restart: unless-stopped
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
#    ports:
#      - "8000:8000"

  bot:
    build:
      context: .
      target: bot
    restart: unless-stopped
    env_file: .env

  worker:
    build:
      context: .
      target: worker
    restart: "no"
    env_file: .env

volumes:
  pgdata:

